import type { BatteryStation } from '@/types';

export const mockStations: BatteryStation[] = [
  {
    id: 'ST001',
    name: 'King Fahd District',
    district: 'King Fahd Road',
    city: 'Riyadh',
    coordinates: { lat: 24.7136, lng: 46.6753 },
    available: 12,
    charging: 5,
    inUse: 3,
    totalCapacity: 20,
    avgWaitTimeMinutes: 5,
    todaySwaps: 89,
    type: 'swap',
  },
  {
    id: 'ST002',
    name: 'Olaya Hub',
    district: 'Olaya Street',
    city: 'Riyadh',
    coordinates: { lat: 24.7236, lng: 46.6853 },
    available: 8,
    charging: 4,
    inUse: 3,
    totalCapacity: 15,
    avgWaitTimeMinutes: 8,
    todaySwaps: 67,
    type: 'swap',
  },
  {
    id: 'ST003',
    name: 'Al Malqa Station',
    district: 'Al Malqa District',
    city: 'Riyadh',
    coordinates: { lat: 24.7836, lng: 46.6453 },
    available: 15,
    charging: 2,
    inUse: 1,
    totalCapacity: 18,
    avgWaitTimeMinutes: 3,
    todaySwaps: 54,
    type: 'fast_charge',
  },
  {
    id: 'ST004',
    name: 'Diplomatic Quarter',
    district: 'Diplomatic Quarter',
    city: 'Riyadh',
    coordinates: { lat: 24.6836, lng: 46.6253 },
    available: 6,
    charging: 8,
    inUse: 2,
    totalCapacity: 16,
    avgWaitTimeMinutes: 12,
    todaySwaps: 92,
    type: 'swap',
  },
  {
    id: 'ST005',
    name: 'Granada Center',
    district: 'Granada Business Park',
    city: 'Riyadh',
    coordinates: { lat: 24.8136, lng: 46.7253 },
    available: 10,
    charging: 3,
    inUse: 1,
    totalCapacity: 14,
    avgWaitTimeMinutes: 6,
    todaySwaps: 73,
    type: 'fast_charge',
  },
  {
    id: 'ST006',
    name: 'Riyadh Park',
    district: 'Riyadh Park Mall',
    city: 'Riyadh',
    coordinates: { lat: 24.7536, lng: 46.6453 },
    available: 4,
    charging: 6,
    inUse: 2,
    totalCapacity: 12,
    avgWaitTimeMinutes: 15,
    todaySwaps: 81,
    type: 'swap',
  },
  {
    id: 'ST007',
    name: 'Al Nakheel Plaza',
    district: 'Al Nakheel District',
    city: 'Riyadh',
    coordinates: { lat: 24.7636, lng: 46.6953 },
    available: 14,
    charging: 4,
    inUse: 4,
    totalCapacity: 22,
    avgWaitTimeMinutes: 4,
    todaySwaps: 95,
    type: 'fast_charge',
  },
  {
    id: 'ST008',
    name: 'Kingdom Tower',
    district: 'King Fahd Road',
    city: 'Riyadh',
    coordinates: { lat: 24.7113, lng: 46.6745 },
    available: 3,
    charging: 7,
    inUse: 3,
    totalCapacity: 13,
    avgWaitTimeMinutes: 10,
    todaySwaps: 64,
    type: 'swap',
  },
];
