import type { Vehicle } from '@/types';

export const mockVehicles: Vehicle[] = [
  {
    id: 'M001',
    plateNumber: 'H A 1234',
    model: 'VegoMax Pro',
    status: 'active',
    batteryLevel: 85,
    location: 'Downtown',
    coordinates: { lat: 24.7136, lng: 46.6753 },
    assignedDriverId: 'Driv-1004',
    assignedDriverName: 'John Smith',
    lastTripAt: new Date(Date.now() - 2 * 60_000).toISOString(),
    totalDistanceKm: 1240,
    currentSpeedKmh: 32,
    estimatedRangeKm: 68,
    speedLimitKmh: 30,
    isLocked: false,
    isEngineRunning: true,
    gpsSignal: 'strong',
    isOnline: true,
  },
  {
    id: 'M002',
    plateNumber: 'H A 1235',
    model: 'VegoMax Pro',
    status: 'active',
    batteryLevel: 72,
    location: 'Central Park',
    coordinates: { lat: 24.7236, lng: 46.6853 },
    assignedDriverId: 'Driv-1002',
    assignedDriverName: 'Sarah Jones',
    lastTripAt: new Date(Date.now() - 5 * 60_000).toISOString(),
    totalDistanceKm: 980,
    currentSpeedKmh: 28,
    estimatedRangeKm: 58,
    speedLimitKmh: 30,
    isLocked: false,
    isEngineRunning: true,
    gpsSignal: 'strong',
    isOnline: true,
  },
  {
    id: 'M003',
    plateNumber: 'H A 1236',
    model: 'VegoLite',
    status: 'charging',
    batteryLevel: 45,
    location: 'North Hub Station',
    coordinates: { lat: 24.7336, lng: 46.6953 },
    lastTripAt: new Date(Date.now() - 15 * 60_000).toISOString(),
    totalDistanceKm: 2340,
    currentSpeedKmh: 0,
    estimatedRangeKm: 36,
    speedLimitKmh: 30,
    isLocked: true,
    isEngineRunning: false,
    gpsSignal: 'strong',
    isOnline: true,
  },
  {
    id: 'M004',
    plateNumber: 'H A 1237',
    model: 'VegoMax Pro',
    status: 'idle',
    batteryLevel: 92,
    location: 'South Point',
    coordinates: { lat: 24.6936, lng: 46.6553 },
    lastTripAt: new Date(Date.now() - 60 * 60_000).toISOString(),
    totalDistanceKm: 1560,
    currentSpeedKmh: 0,
    estimatedRangeKm: 74,
    speedLimitKmh: 30,
    isLocked: true,
    isEngineRunning: false,
    gpsSignal: 'strong',
    isOnline: true,
  },
  {
    id: 'M005',
    plateNumber: 'H A 1238',
    model: 'VegoLite',
    status: 'active',
    batteryLevel: 68,
    location: 'West Side',
    coordinates: { lat: 24.7036, lng: 46.6453 },
    assignedDriverId: 'Driv-1005',
    assignedDriverName: 'Mike Brown',
    lastTripAt: new Date().toISOString(),
    totalDistanceKm: 890,
    currentSpeedKmh: 25,
    estimatedRangeKm: 54,
    speedLimitKmh: 30,
    isLocked: false,
    isEngineRunning: true,
    gpsSignal: 'strong',
    isOnline: true,
  },
  {
    id: 'M006',
    plateNumber: 'H A 1239',
    model: 'VegoMax Pro',
    status: 'idle',
    batteryLevel: 88,
    location: 'East District',
    coordinates: { lat: 24.7236, lng: 46.7053 },
    lastTripAt: new Date(Date.now() - 45 * 60_000).toISOString(),
    totalDistanceKm: 1780,
    currentSpeedKmh: 0,
    estimatedRangeKm: 70,
    speedLimitKmh: 30,
    isLocked: true,
    isEngineRunning: false,
    gpsSignal: 'strong',
    isOnline: true,
  },
  {
    id: 'M007',
    plateNumber: 'H A 1240',
    model: 'VegoLite',
    status: 'maintenance',
    batteryLevel: 0,
    location: 'Service Center',
    coordinates: { lat: 24.7436, lng: 46.6353 },
    lastTripAt: new Date(Date.now() - 2 * 24 * 60 * 60_000).toISOString(),
    totalDistanceKm: 3420,
    currentSpeedKmh: 0,
    estimatedRangeKm: 0,
    speedLimitKmh: 30,
    isLocked: true,
    isEngineRunning: false,
    gpsSignal: 'none',
    isOnline: false,
  },
  {
    id: 'M008',
    plateNumber: 'H A 1241',
    model: 'VegoMax Pro',
    status: 'charging',
    batteryLevel: 22,
    location: 'Downtown Station',
    coordinates: { lat: 24.7136, lng: 46.6753 },
    lastTripAt: new Date(Date.now() - 30 * 60_000).toISOString(),
    totalDistanceKm: 2100,
    currentSpeedKmh: 0,
    estimatedRangeKm: 17,
    speedLimitKmh: 30,
    isLocked: true,
    isEngineRunning: false,
    gpsSignal: 'strong',
    isOnline: true,
  },
];
